### ISSUE TITLE
In edit order page, options for print invoice, delivery note and print receipt is not visible. 

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/woocommerce-delivery-notes#101]
After new release, in edit order page, options like a print invoice, delivery note, and the print receipt is not visible. It was visible before an update was released.

Screenshot: https://prnt.sc/ovjjzm

**Comment by ashokrane** [comment]
@kenil802 This has been fixed in v4.5.1. Please let the client know about it.
