### ISSUE TITLE
Debug log file shows this error too

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-notes#11]
The WC_Order::get_order_currency function is deprecated since version 3.0. Replace with WC_Order::get_currency.

This error i can not able to replicate..this issue raised by client Jos Klever.

**Comment by bhagyashri12345** [comment]
This issue has been replicated. 
When you have refund product then this warning comes on order invoice.

**Comment by vishalck** [comment]
@apeksha10 Please try to replicate this & let us know if you find this error.

**Comment by apeksha10** [comment]
Yes.. i am able to replicate this issue.
1. Take any product (Variable or Simple)
2. Placed the order
3. Refund this order
4. Update this order
5. Click Print button on Delivery notes then i got the above notice
