### ISSUE TITLE
All features/options are missing in the documentation

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/woocommerce-delivery-notes#110]
All features/options are missing in the documentation.

**Comment by tedioustanisha** [comment]
@Chetna1510 @geogirish @upenkapse @priyanka-tychesoftwares 

pls guide me regarding this because i cannot find any documentation page for this plugin

**Comment by tedioustanisha** [comment]
**installation and activation doc:** 

preview link: https://www.tychesoftwares.com/docs/?post_type=docs&p=14124&preview=true
edit link: https://www.tychesoftwares.com/docs/wp-admin/post.php?post=14124&action=edit


**changelog doc**

preview link: https://www.tychesoftwares.com/docs/docs/print-invoice-delivery-notes-for-woocommerce/changelog/
edit link: https://www.tychesoftwares.com/docs/wp-admin/post.php?action=edit&post=14127


pls review @geogirish

**Comment by tedioustanisha** [comment]
**customizing template doc**

preview link: https://www.tychesoftwares.com/docs/?post_type=docs&p=14126&preview=true
edit link: https://www.tychesoftwares.com/docs/wp-admin/post.php?post=14126&action=edit

**installation and activation doc** 

preview link: https://www.tychesoftwares.com/docs/?post_type=docs&p=14124&preview=true
edit link: https://www.tychesoftwares.com/docs/wp-admin/post.php?action=edit&post=14124

**changelog doc**
https://www.tychesoftwares.com/docs/docs/print-invoice-delivery-notes-for-woocommerce/changelog/

**Comment by gaminikhil** [comment]
we have updated our Document. and added all new and old features/options in that. hence i am closing this issue.
