### ISSUE TITLE
Security: Anybody can view the print-view of any order /print-order/1234 without authentication

### ISSUE THREAD

**Issue by Schroeffu** [TycheSoftwares/woocommerce-delivery-notes#112]
Hello there,

first of all, this plugin looks very nice in the backend and seems to be very useful.
Unfortunately, I can open ANY order with its order-number, even in browser private session (not authenticated to wordpress, no cookies)

Example URL which is view-able for anybody, woocommerce order number 2343: https://mydomain.com/print-oder/2343 can be accessed from anybody 

This leaks at least customer e-mail address and their products with date and price etc.

Best Regards

**Comment by ethan-tqa** [comment]
I tested and it does not behave like you described. The printing URL should be as follow:

`https://yourdomain.com/my-account/print-order/125356/`

Naturally, if you are a logged in customer, it prints out as expected. 
If you logged in to an account that does not own this order, it redirects back to your account page. 
If you are not logged in, you see a blank page.

**Comment by Schroeffu** [comment]
Strange, you are right. Today i tested it again with some orders and have also a white page when not logged in, or directly another browser in use. Maybe my first test still had somewhere the admin login in use in the background. Sorry, my false.

So not logged in users will nothing see but only the white page, when they click on "print order" in the eMail link right? Maybe a one-time-url for the mail print link would be an enhancement, but ok for the moment. 

Sorry again.

**Comment by ashokrane** [comment]
Thank you @Schroeffu @ethan-tqa for testing this out.

You're right that we could have a one-time url for the print link, we will explore the possibility of that.

**Comment by apeksha10** [comment]
@Schroeffu @ethan-tqa

I tested the above scenarios in 2 ways 
1.  If any client opens the above link from My account page into a private browser then it is redirected to a blank page
2. but if any client copies the link from customer email and opens into the private browser then it will be redirected to that Invoice page.

For example, Any client open this link from customer email "https://mydomain.com/my-account/print-order/115" then it is redirected to a blank page
but client "https://mydomain.com/my-account/print-order/115/?print-order-type=invoice&print-order-email=apeksha@tychesoftwares.com" open this link then it is redirecting to Invoice page
So it is the correct behavior
No one can access the customer's user account
