### ISSUE TITLE
When i complete the order and click on print invoice then i got an error on debug log file

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-notes#12]
Product type : Simple product

Here when i placed the order and complete the order then click on print Invoice then i got this notice.

[04-Sep-2017 06:30:07 UTC] The WC_Order_Item_Meta::__construct function is deprecated since version 3.1. Replace with WC_Order_Item_Product.

**Comment by apeksha10** [comment]
The Same issue replicated when i complete the order and click on print delivery notes

**Comment by moxajogani** [comment]
I could not replicate this issue. When the order is marked as completed and then when I try to print invoice or delivery notes for that order. There are no warnings or notices shown in the debug.log file. Hence closing this issue.
