### ISSUE TITLE
Tracker cron event not running properly

### ISSUE THREAD

**Issue by dhruvins** [TycheSoftwares/woocommerce-delivery-notes#122]
`WCDN_TS_Tracker::ts_send_tracking_data()` cron event not triggering correctly.

When these events are viewed in Cron Schedules, it appears to have been running every minute.

Ideally it should run every week

Related forum: https://wordpress.org/support/topic/wcdn_ts_trackerts_send_tracking_data/

**Comment by kenil802** [comment]
One more client has asked for this.

Link: https://wordpress.org/support/topic/wcdn_ts_tracker_send_event-always-in-cron-queue/

**Comment by kenil802** [comment]
One client has faced this issue:

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/20135

**Comment by kokomomtl** [comment]
I'm having the same issue. Will this be resolved soon?

**Comment by ashokrane** [comment]
@kokomomtl Yes, we will be resolving this in the next update.

**Comment by Shasvat7** [comment]
@kokomomtl we have fixed this issue & have included it in the v4.6.1 . So please update your plugin & check it once.
