### ISSUE TITLE
Hiding Child Products in Composite Products in the Invoice and Delivery Notes

### ISSUE THREAD

**Issue by dhruvins** [TycheSoftwares/woocommerce-delivery-notes#125]
There have been request to hide the child products in Invoices.

We must achieve this via some filters.

Related Forum: https://wordpress.org/support/topic/hiding-composite-items/

**Comment by dhruvins** [comment]
One more client had requested this:
https://wordpress.org/support/topic/composite-products-14/

**Comment by dhruvins** [comment]
Requested a year ago as well:
https://wordpress.org/support/topic/exclude-composite-and-bundled-products-line-items-from-receipt-and-or-invoice/

**Comment by Shasvat7** [comment]
Snippet code of the filter to be used to hide the child products in composite products :- https://github.com/TycheSoftwares/woocommerce-delivery-notes/wiki/Hooks-and-Filters-for-compatibility-and-minor-changes#this-will-hide-the-child-products-in-composite-products
