### ISSUE TITLE
Option to set the size of the logo

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/woocommerce-delivery-notes#128]
The client wants us to add the feature or option which includes the size of the logo.

Link: https://wordpress.org/support/topic/change-logo-size-25/

**Comment by kenil802** [comment]
Another client has asked for the same:

link: https://wordpress.org/support/topic/how-to-change-logo-size-3/

**Comment by gaminikhil** [comment]
We added this logo resize option in our new UI. hence i am closing this issue.
