### ISSUE TITLE
Bulk Printing is not working

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/woocommerce-delivery-notes#130]
The client is having an issue where bulk printing options are not working.

However, on our site, it is working fine.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/18345

**Comment by kenil802** [comment]
Another client has also faced this issue.

Link: https://wordpress.org/support/topic/no-bulk-printing/

**Comment by kenil802** [comment]
The same issue has been faced again.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/18936

**Comment by kenil802** [comment]
Another client has reposted the same issue.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/18668

**Comment by kenil802** [comment]
Another client has the same issue.

Link: https://wordpress.org/support/topic/no-print-bulk-order-delivery/

**Comment by kenil802** [comment]
One more client.

Link: https://wordpress.org/support/topic/no-print-bulk-order-delivery-2/

**Comment by Shasvat7** [comment]
This issue is been replicated when some other plugin is activated on our site. Like when the PRDD plugin is activated we will be able to replicate the issue on our site.
