### ISSUE TITLE
Currency not showing correct symbol when working with WC Currency Switcher.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/woocommerce-delivery-notes#133]
The client wants to make our plugin compatible with the WooCommerce Currency Switcher. 

I have tested with the Currency Switcher plugin and found that this plugin by default sets the default currency which is set on the orders page in spite of having the other currencies too.

Link: https://wordpress.org/support/topic/currency-not-showing-correct-symbol/

Plugin link: https://wordpress.org/plugins/woocommerce-currency-switcher/

**Comment by gaminikhil** [comment]
This issue has been resolved. i am not able to replicate with 5.2.0 version. [https://prnt.sc/Gr23eqv98Lb9](https://prnt.sc/Gr23eqv98Lb9). hence i am closing this issue.
