### ISSUE TITLE
Console shows some error after activating plugin

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-notes#140]
Describe the bug
Console shows some error after activating plugin.

To Reproduce

1. on my local I don't have orddd lite plugin install
2. After installing the plugin, plugin page throws an error

Expected behavior
No error should be display

**Comment by ashokrane** [comment]
@apeksha10 AC Lite? What exactly you are trying to say here?

**Comment by apeksha10** [comment]
Sorry.. by mistake I wrote Ac lite in the issue. Rectified

**Comment by ashokrane** [comment]
@apeksha10 What are you trying to say in the issue? It's still unclear.

**Comment by apeksha10** [comment]
I am not able to replicate the above issue with the latest Orddd lite with Print Invoice plugin.
Issue is invalid
Hence closed this issue
