### ISSUE TITLE
Shows error in the debug file with WooCommerce version 4.4.1

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/woocommerce-delivery-notes#143]
The issue is the error appears in the debug file when working with the WooCommerce version 4.4.1.

Error: “PHP message: The WC_Abstract_Legacy_Order::get_product_from_item function is deprecated since version 4.4.0. Replace with $item->get_product()”

Steps to replicate:
1) Activate the plugin
2) Print the order
3) Check the debug file and the error will be shown.

Link: https://wordpress.org/support/topic/deprecated-function-in-plugin-update-needed/

**Comment by Shasvat7** [comment]
Fixed this issue in this PR :- https://github.com/TycheSoftwares/woocommerce-delivery-notes/pull/142
