### ISSUE TITLE
Product Image does not appear in the invoice with the latest version of WC

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/woocommerce-delivery-notes#154]
**Describe the bug**
The issue is that the product image does not appear on the invoice when we click on the invoice button on the Orders page with the latest version of Wc 4.6.1

**To Reproduce**
1) Place an order which has the product image.
2) Click on the Invoice button on the Order list page. You will not see the product image there.
3) Go to the Edit Order page, there click on the Print Invoice button, you will see the product image.

**Expected behavior**
The product image should appear in both cases. i.e from the Order list page and from the Edit Order page also.

The issue is not been replicated with the lower version of the WooCommerce. 

Link: https://wordpress.org/support/topic/after-woo-update-images-no-longer-print-from-orders-field/#post-13596107

**Comment by DMKITServices** [comment]
any updates on this as we have the same problem

**Comment by kenil802** [comment]
One more client has faced the same issue.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/22212

**Comment by Shasvat7** [comment]
Hi @DMKITServices 

Please add the below code in your functions.php file of your active theme and check whether the  image is coming or not.
Code :

```
/**
 * Add this code snippet in functions.php file of your currently active theme.
 * An example that adds a 40px large product image.
 */
function example_product_image( $product ) {    
    if( isset( $product->id ) && has_post_thumbnail( $product->id ) ) {
        echo get_the_post_thumbnail( $product->id, array( 40, 40 ), array( 'loading' => false ) );
    }
}
add_action( 'wcdn_order_item_before', 'example_product_image' );
```
