### ISSUE TITLE
Add deactivation survey v2

### ISSUE THREAD

**Issue by pinalj** [TycheSoftwares/woocommerce-delivery-notes#231]
Is your feature request related to a problem? Please describe.
Add the deactivation survey v2 in the plugin.

Describe the solution you'd like
Tyche Javascript Constructor: https://github.com/TycheSoftwares/tyche-js-constructor
Plugin Deactivation: https://github.com/TycheSoftwares/tyche-plugin-deactivation

The description of the usage is in the README.md files of the respective repos.

**Comment by mokshasharmila13** [comment]
This code only tracks the ID and doesn't save the deactivation reason.

**Comment by apeksha10** [comment]
Re-open this issue, after clicking on "Reset" button, no action run 

https://prnt.sc/UaCRPd543Txb
