### ISSUE TITLE
"OOPS! THAT PAGE CAN’T BE FOUND" message is come on Order Received page and My Account page

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-notes#29]
Print invoice and delivery note plugin version:4.3.5
After placing the order the order received page when I click on the Print button then I found the above massage.
same way from My account page when I click on the Print button the same message will come.
https://www.screencast.com/t/IlCx1XaA

**Comment by moxajogani** [comment]
We have a FAQ mentioned in our plugin about 404 error. If we face this we have to save the permalink settings again or the settings from the plugin. https://screencast.com/t/yziUfOMnl9ek

**Comment by moxajogani** [comment]
We could not replicate this with the new WordPress installation with default permalinks settings and default plugin settings. Hence closing this issue. 

Also, it is not being replicated on @apeksha10 local as well now.
