### ISSUE TITLE
Icons Missing on Action Buttons

### ISSUE THREAD

**Issue by szuranski** [TycheSoftwares/woocommerce-delivery-notes#37]
After upgrading WooCommerce to v3.3.1 the icons no longer appear on the action buttons for _Print Invoice_ and _Print Delivery Note_. There were other plugins that had the same problem but updating those plugins resolved the issue.

WordPress 4.9.4
WooCommerce 3.3.1
WooCommerce Print Invoice & Delivery Note 4.4.1

![image](https://user-images.githubusercontent.com/4400466/35957615-1afd099a-0c62-11e8-8c0a-497b61df3595.png)

**Comment by szuranski** [comment]
Looks like there was a class name change from _column-order_actions_ to _column-wc_actions_.

![image](https://user-images.githubusercontent.com/4400466/35958769-26fd9d30-0c68-11e8-91a2-227f4f3577dd.png)

![image](https://user-images.githubusercontent.com/4400466/35958846-9748cfec-0c68-11e8-8911-fc88ff8eb5f4.png)

**Comment by hjoelr** [comment]
This has been fixed in version 4.4.2 which includes commit dd834210d6c1d64be433dd0781e0a15ba3142e1c.

**Comment by moxajogani** [comment]
As the fix for this issue is released in version 4.4.2, closing this issue.
