### ISSUE TITLE
crash after updating woocommerce pointing to this plugin

### ISSUE THREAD

**Issue by karenkirk** [TycheSoftwares/woocommerce-delivery-notes#379]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After updating some plugins my site crashed and it appears to indicate an issue with the print invoice and delivery plugingin.
Details below
When seeking help with this issue, you may be asked for some of the following information:

WordPress version 6.6.1

Active theme: Astra Child (version 1.0.0) Current plugin: Print Invoice & Delivery Notes for WooCommerce (version 5.1.0) PHP version 7.4.33

Error Details

=============

An error of type E_ERROR was caused in line 273 of the file /home/makemybe/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/class-woocommerce-delivery-notes.php. Error message: Uncaught Error: Call to undefined function as_next_scheduled_action() in /home/makemybe/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/class-woocommerce-delivery-notes.php:273

Stack trace:

#0 /home/makemybe/public_html/wp-includes/class-wp-hook.php(324): WooCommerce_Delivery_Notes->wcdn_create_dir('')

#1 /home/makemybe/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)

#2 /home/makemybe/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)

#3 /home/makemybe/public_html/wp-settings.php(700): do_action('init')

#4 /home/makemybe/public_html/wp-config.php(93): require_once('/home/makemybe/...')

#5 /home/makemybe/public_html/wp-load.php(50): require_once('/home/makemybe/...')

#6 /home/makemybe/public_html/wp-admin/admin.php(34): require_once('/home/makemybe/...')

#7 /home/makemybe/public_html/wp-admin/update.php(16): require_once('/home/makemybe/...')

#8 {main}

  thrown
[Expand](https://wordpress.org/support/topic/plugin-caused-site-to-crash-after-upgrading-woocommerce/#)

### Steps to reproduce

activate print invoice and delivery note plugin

### Expected behavior

to not crash the site

### WordPress Environment

<html>
<body>

WordPress environment
--
WordPress address (URL): |   | https://makemybear.com.au
Site address (URL): |   | https://makemybear.com.au
WooCommerce version: |   | 9.1.4
WooCommerce Legacy REST API package: |   | 1.0.4 /home/makemybe/public_html/wp-content/plugins/woocommerce-legacy-rest-api/includes
Action Scheduler package: |   | 3.7.4 /home/makemybe/public_html/wp-content/plugins/woocommerce/packages/action-scheduler
Log directory writable: |   | /home/makemybe/public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 6.6.1
WordPress multisite: |   | –
WordPress memory limit: |   | 768 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   |  

</body>
</html>WordPress environment
WordPress address (URL):		https://makemybear.com.au
Site address (URL):		https://makemybear.com.au
WooCommerce version:		9.1.4
WooCommerce Legacy REST API package:		 1.0.4 /home/makemybe/public_html/wp-content/plugins/woocommerce-legacy-rest-api/includes
Action Scheduler package:		 3.7.4 /home/makemybe/public_html/wp-content/plugins/woocommerce/packages/action-scheduler
Log directory writable:		 /home/makemybe/public_html/wp-content/uploads/wc-logs/
WordPress version:		6.6.1
WordPress multisite:		–
WordPress memory limit:		768 MB
WordPress debug mode:		–
WordPress cron:		
Language:		en_US
External object cache:		
Server environment
Server info:		LiteSpeed
PHP version:		7.4.33
PHP post max size:		128 MB
PHP time limit:		300
PHP max input vars:		10000
cURL version:		7.87.0, OpenSSL/1.1.1w
SUHOSIN installed:		–
MySQL version:		5.5.5-10.5.22-MariaDB-cll-lve
Max upload size:		128 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WooCommerce database version:		9.1.4
Database prefix	 	wp_
Total Database Size	 	473.00MB
Database Data Size	 	409.05MB
Database Index Size	 	63.95MB
wp_woocommerce_sessions	 	Data: 1.49MB + Index: 0.03MB + Engine MyISAM
wp_woocommerce_api_keys	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items	 	Data: 1.67MB + Index: 1.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta	 	Data: 14.71MB + Index: 9.41MB + Engine MyISAM
wp_woocommerce_tax_rates	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_log	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_actionscheduler_actions	 	Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wpstg2_actionscheduler_claims	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_actionscheduler_groups	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpstg2_actionscheduler_logs	 	Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wpstg2_commentmeta	 	Data: 0.20MB + Index: 0.14MB + Engine MyISAM
wpstg2_comments	 	Data: 2.54MB + Index: 1.05MB + Engine MyISAM
wpstg2_duplicator	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_ebayaffinity_categories	 	Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wpstg2_ebayaffinity_categories_bak	 	Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wpstg2_ebayaffinity_itemspecific_mapping	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpstg2_ebayaffinity_log	 	Data: 6.40MB + Index: 0.17MB + Engine MyISAM
wpstg2_ebayaffinity_pushtoken	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpstg2_ebayaffinity_shiprules	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_ebayaffinity_titlerules	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_layerslider	 	Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wpstg2_links	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_options	 	Data: 147.27MB + Index: 11.78MB + Engine MyISAM
wpstg2_postmeta	 	Data: 11.31MB + Index: 5.13MB + Engine MyISAM
wpstg2_posts	 	Data: 3.07MB + Index: 0.37MB + Engine MyISAM
wpstg2_termmeta	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpstg2_terms	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_term_relationships	 	Data: 0.03MB + Index: 0.05MB + Engine MyISAM
wpstg2_term_taxonomy	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpstg2_usermeta	 	Data: 0.59MB + Index: 0.32MB + Engine MyISAM
wpstg2_users	 	Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wpstg2_wc_admin_notes	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_wc_admin_note_actions	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_wc_category_lookup	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_wc_customer_lookup	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpstg2_wc_download_log	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_wc_order_coupon_lookup	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_wc_order_product_lookup	 	Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wpstg2_wc_order_stats	 	Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpstg2_wc_order_tax_lookup	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpstg2_wc_product_meta_lookup	 	Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wpstg2_wc_tax_rate_classes	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpstg2_wc_webhooks	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_woocommerce_api_keys	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_woocommerce_attribute_taxonomies	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpstg2_woocommerce_bundled_itemmeta	 	Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wpstg2_woocommerce_bundled_items	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_woocommerce_downloadable_product_permissions	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_woocommerce_log	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_woocommerce_order_itemmeta	 	Data: 6.61MB + Index: 4.24MB + Engine MyISAM
wpstg2_woocommerce_order_items	 	Data: 0.80MB + Index: 0.48MB + Engine MyISAM
wpstg2_woocommerce_payment_tokenmeta	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_woocommerce_payment_tokens	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_woocommerce_sessions	 	Data: 4.59MB + Index: 0.08MB + Engine MyISAM
wpstg2_woocommerce_shipping_zones	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_woocommerce_shipping_zone_locations	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_woocommerce_shipping_zone_methods	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_woocommerce_tax_rates	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpstg2_woocommerce_tax_rate_locations	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_yith_wcwl	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_yoast_indexable	 	Data: 0.31MB + Index: 0.04MB + Engine MyISAM
wpstg2_yoast_indexable_hierarchy	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_yoast_migrations	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpstg2_yoast_primary_term	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpstg2_yoast_seo_links	 	Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wpstg2_yoast_seo_meta	 	Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_actions	 	Data: 0.07MB + Index: 0.04MB + Engine MyISAM
wp_actionscheduler_claims	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs	 	Data: 0.04MB + Index: 0.04MB + Engine MyISAM
wp_commentmeta	 	Data: 0.22MB + Index: 0.15MB + Engine MyISAM
wp_comments	 	Data: 4.58MB + Index: 1.73MB + Engine MyISAM
wp_duplicator	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ebayaffinity_categories	 	Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_ebayaffinity_categories_bak	 	Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_ebayaffinity_itemspecific_mapping	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_ebayaffinity_log	 	Data: 6.40MB + Index: 0.17MB + Engine MyISAM
wp_ebayaffinity_pushtoken	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_ebayaffinity_shiprules	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ebayaffinity_titlerules	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_e_events	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes	 	Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations	 	Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions	 	Data: 0.53MB + Index: 0.42MB + Engine MyISAM
wp_e_submissions_actions_log	 	Data: 0.09MB + Index: 0.13MB + Engine MyISAM
wp_e_submissions_values	 	Data: 1.47MB + Index: 0.15MB + Engine MyISAM
wp_layerslider	 	Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_links	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_url	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file	 	Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_options	 	Data: 148.75MB + Index: 11.83MB + Engine MyISAM
wp_phone_orders_log	 	Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_pimwick_gift_card	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pimwick_gift_card_activity	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_postmeta	 	Data: 23.97MB + Index: 10.27MB + Engine MyISAM
wp_posts	 	Data: 4.61MB + Index: 0.61MB + Engine MyISAM
wp_smush_dir_images	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_relationships	 	Data: 0.03MB + Index: 0.06MB + Engine MyISAM
wp_term_taxonomy	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_usermeta	 	Data: 1.05MB + Index: 0.57MB + Engine MyISAM
wp_users	 	Data: 0.05MB + Index: 0.04MB + Engine MyISAM
wp_wc_admin_notes	 	Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions	 	Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup	 	Data: 0.10MB + Index: 0.07MB + Engine MyISAM
wp_wc_download_log	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_orders	 	Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses	 	Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup	 	Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_operational_data	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup	 	Data: 1.27MB + Index: 0.91MB + Engine MyISAM
wp_wc_order_stats	 	Data: 0.27MB + Index: 0.14MB + Engine MyISAM
wp_wc_order_tax_lookup	 	Data: 0.14MB + Index: 0.15MB + Engine MyISAM
wp_wc_product_attributes_lookup	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup	 	Data: 0.03MB + Index: 0.05MB + Engine MyISAM
wp_wc_rate_limits	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_bundled_itemmeta	 	Data: 0.04MB + Index: 0.04MB + Engine MyISAM
wp_woocommerce_bundled_items	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wss_log	 	Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable	 	Data: 0.35MB + Index: 0.06MB + Engine MyISAM
wp_yoast_indexable_hierarchy	 	Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_yoast_migrations	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term	 	Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_yoast_seo_links	 	Data: 0.10MB + Index: 0.03MB + Engine MyISAM
wp_yoast_seo_meta	 	Data: 0.01MB + Index: 0.01MB + Engine MyISAM
Post Type Counts
attachment	 	719
bl_testimonials	 	24
create-portfolio	 	1
custom_css	 	2
elementor_library	 	6
nav_menu_item	 	57
oembed_cache	 	3
page	 	60
post	 	2
product	 	374
product_variation	 	35
revision	 	717
shop_coupon	 	10
shop_order	 	6043
shop_order_refund	 	21
wpt_product_table	 	1
wp_font_face	 	33
wp_font_family	 	12
wp_global_styles	 	1
yiw_gallery	 	6
Security
Secure connection (HTTPS):		
Hide errors from visitors		
Active plugins (22)
[Akismet Anti-spam: Spam Protection](https://akismet.com/)	 	by Automattic - Anti-spam Team – 5.3.3
[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/)	 	by Elementor.com – 3.23.1
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash)	 	by Elementor.com – 3.23.3
[LiteSpeed Cache](https://www.litespeedtech.com/products/cache-plugins/wordpress-acceleration)	 	by LiteSpeed Technologies – 6.3.0.1
Phone Orders for WooCommerce	 	by AlgolPlus – 3.9.0
[PW WooCommerce Gift Cards](https://www.pimwick.com/gift-cards/)	 	by Pimwick, LLC – 2.0
[Regenerate Thumbnails](https://alex.blog/wordpress-plugins/regenerate-thumbnails/)	 	by Alex Mills (Viper007Bond) – 3.1.6
[CTX Feed](https://webappick.com/)	 	by WebAppick – 6.5.9
Advanced Order Export For WooCommerce	 	by AlgolPlus – 3.5.3
[Preview E-mails for WooCommerce](https://www.digamberpradhan.com/preview-e-mails-for-woocommerce/)	 	by Digamber Pradhan – 2.2.13
[Product Table for WooCommerce by CodeAstrology (WooproductTable)](https://wooproducttable.com/pricing/?utm_source=WPT+Plugin+Dashboard&utm_medium=Free+Version)	 	by CodeAstrology Team – 3.5.0
Stock Sync for WooCommerce Pro	 	by Lauri Karisola / WP Trio – 2.6.2
WooCommerce.com Update Manager	 	by Automattic – 1.0.3
[WooCommerce Stripe Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/)	 	by WooCommerce – 8.5.2
[WooCommerce Legacy REST API](https://github.com/woocommerce/woocommerce-legacy-rest-api)	 	by WooCommerce – 1.0.4
[WooCommerce PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/)	 	by WooCommerce – 2.8.2
[WooCommerce Pro Shipping](http://plugins.leewillis.co.uk/store/plugins/woocommerce-pro-shipping)	 	by Lee Willis – 1.3.9
[Woo Product Bundles](https://woocommerce.com/products/product-bundles/)	 	by Woo – 8.0.0 (update to version 8.0.1 is available)
[Sequential Order Numbers for WooCommerce](http://www.skyverge.com/blog/woocommerce-sequential-order-numbers/)	 	by SkyVerge – 1.10.1
[WooCommerce](https://woocommerce.com/)	 	by Automattic – 9.1.4
[Yoast SEO](https://yoa.st/1uj)	 	by Team Yoast – 23.1
[Smush](http://wordpress.org/plugins/wp-smushit/)	 	by WPMU DEV – 3.16.5
Inactive plugins (6)
[Google Analytics for WooCommerce](https://wordpress.org/plugins/woocommerce-google-analytics-integration/)	 	by WooCommerce – 2.0.6
[LayerSlider WP](http://codecanyon.net/user/kreatura/)	 	by Kreatura Media – 5.6.2
[Print Invoice & Delivery Notes for WooCommerce](https://www.tychesoftwares.com/)	 	by Tyche Softwares – 5.1.0
[Product Import Export for WooCommerce](https://wordpress.org/plugins/product-import-export-for-woo/)	 	by WebToffee – 2.4.4
[WP Migrate DB](http://wordpress.org/plugins/wp-migrate-db/)	 	by Delicious Brains – 1.0
[WP Staging](https://wordpress.org/plugins/wp-staging)	 	by WP-Staging – 2.7.2
Dropin Plugins ()
maintenance.php	 	maintenance.php
object-cache.php	 	LiteSpeed Cache - Object Cache (Drop-in)
Must Use Plugins (1)
[WP Staging Optimizer](https://wp-staging.com/)	 	by René Hermenau – 1.2
Settings
API enabled:		
Force SSL:		–
Currency		AUD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		bundle (bundle), external (external), grouped (grouped), pw gift card (pw-gift-card), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
Connected to WooCommerce.com:		
Enforce Approved Product Download Directories:		–
HPOS enabled:		–
Order datastore:		WC_Order_Data_Store_CPT
HPOS data sync enabled:		–
Logging
Enabled		
Handler		Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period		30 days
Level threshold		–
Log directory size		318 KB
WooCommerce pages
[Shop base](https://makemybear.com.au/wp-admin/post.php?post=4&action=edit):		#4 - /shop/
[Cart](https://makemybear.com.au/wp-admin/post.php?post=6486&action=edit):		#6486 - /new-cart/ -  Contains the [woocommerce_cart] shortcode
[Checkout](https://makemybear.com.au/wp-admin/post.php?post=6&action=edit):		#6 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
[My account](https://makemybear.com.au/wp-admin/post.php?post=8&action=edit):		#8 - /my-account/
[Terms and conditions](https://makemybear.com.au/wp-admin/post.php?post=4445&action=edit):		#4445 - /terms-conditions/
Theme
Name:		Astra Child
Version:		1.0.0
Author URL:		http://wpastra.com/about/
Child theme:		
Parent theme name:		Astra
Parent theme version:		4.7.3
Parent theme author URL:		https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce support:		
Templates
Overrides	 	astra-child/woocommerce/emails/customer-completed-order.php
Product Bundles
Database version:		8.0.0
Loopback test:		
Template overrides:		–
WooCommerce PayPal Payments
Onboarded		
Shop country code		AU
WooCommerce currency supported		
Advanced Card Processing available in country		
Pay Later messaging available in country		
Webhook status		
PayPal Vault enabled		–
ACDC Vault enabled		–
Logging enabled		–
Reference Transactions		–
Used PayPal Checkout plugin		–
Subscriptions Mode		Disabled
Admin
Enabled Features:		activity-panels, analytics, product-block-editor, coupons, core-profiler, customize-store, customer-effort-score-tracks, import-products-task, experimental-fashion-sample-products, shipping-smart-defaults, shipping-setting-tour, homescreen, marketing, mobile-app-banner, navigation, onboarding, onboarding-tasks, product-custom-fields, remote-inbox-notifications, remote-free-extensions, payment-gateway-suggestions, shipping-label-banner, subscriptions, store-alerts, transient-notices, woo-mobile-welcome, wc-pay-promotion, wc-pay-welcome-page, launch-your-store
Disabled Features:		experimental-blocks, minified-js, pattern-toolkit-full-composability, product-pre-publish-modal, printful, settings, async-product-editor-category-field, product-editor-template-system
Daily Cron:		 Next scheduled: 2024-08-01 05:20:27 +00:00
Options:		
Notes:		213
Onboarding:		completed
Action Scheduler
Version:	3.7.4
Data store:	ActionScheduler_DBStore
Action Status	 	Count	Oldest Scheduled Date	Newest Scheduled Date
Complete	 	240	2024-06-30 15:38:27 +0000	2024-07-31 03:43:23 +0000
Failed	 	8	2023-03-08 04:19:16 +0000	2024-07-31 08:23:13 +0000
Pending	 	2	2024-08-01 03:43:18 +0000	2024-08-01 08:23:13 +0000
Status report information
Generated at:	 	2024-07-31 08:47:51 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only our plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by gaminikhil** [comment]
I am closing this issue. It occurred due to a WooCommerce update glitch. After reactivating the plugin, the issue could not be replicated.
