### ISSUE TITLE
Buttons are not displayed on woocommerce order page 

### ISSUE THREAD

**Issue by mokshasharmila13** [TycheSoftwares/woocommerce-delivery-notes#385]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the WooCommerce order page, a meta box for our plugin usually appears by default, displaying three buttons: Print Invoice, Print Receipt, and Print Delivery Notes. However, these buttons are not showing at the moment.

### Steps to reproduce

1. Activate our plugin.
2. Go to the WooCommerce order page and then click on the "Edit Order" page.

![image](https://github.com/user-attachments/assets/f6de56a9-9c91-44a8-9942-04200573c6b7)

### Expected behavior

Make sure all the buttons appear, regardless of whether they are default or simple type.

### WordPress Environment

No

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only our plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by priyanka-tychesoftwares** [comment]
One client has reported this issue. I am unable to replicate this issue on my staging site. But I am able to replicate it on the client's site. 
Screenshot: https://app.screencast.com/emWiycGkwE80e

He has also shared the screenshot of errors: https://app.screencast.com/E0EMCTQOO0ix0 I am able to replicate these errors on my site.

Ticket link: https://support.tychesoftwares.com/conversation/5009?folder_id=15
