### ISSUE TITLE
Point out the setting set up given in link on welcome page 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-notes#49]
On welcome page click on this setting link "Enable Print button for Customers" we should point out the particular setting set up

see the screenshot: https://www.screencast.com/t/pACUD2rcbf

same way in "Enable Invoice Numbering" settings

**Comment by moxajogani** [comment]
As we have removed the welcome page in this commit: cd4dfc51fde8f326aeeaedab4e3d9c6424cf25c3

This is not a valid issue now. Hence closing this.
