### ISSUE TITLE
Deposits notice is display even if Deposits plugin activate on my site

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-notes#52]
Deposit notice display even if Deposits plugin activate on my site

see the screenshot: https://www.screencast.com/t/IzfEUtsz0
https://www.screencast.com/t/pKbua1a4C

**Comment by bhavik-kiri** [comment]
I have git hub copy ( 20-07-2018 @4.30 PM )

I have followed the steps mentioned by @apeksha10 , but not able to replicate the issue.

**Comment by apeksha10** [comment]
This issue is not replicate because on my site the Deposits plugin folder name is wrong after rename that plugin folder name it works fine.

Hence I closed this issue and marked as Fixed
