### ISSUE TITLE
Order page load continues with bulk action

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-notes#76]
Steps
1. Place the order
2. Use bulk action "Print Invoice" option then Order page load continues and No error found on debug log

see the video for better understand: https://www.screencast.com/t/c8gnBgMfYql

**Comment by moxajogani** [comment]
I think this is not an issue. The page is loading because of the print preview option. Once the print action is completed the page stops loading. 

This is not mentioned by any of our clients. Hence closing this issue for now and we will fix if any of the clients mention about this issue later.
